{% set name = "lsdtt-xtensor-python" %}
{% set version = "0.0.4.15" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lsdtt_xtensor_python-{{ version }}.tar.gz
  sha256: 3cea57571178e0a576c881645eac9741a96008733cdb6fa1450aa6a98cadff70

build:
  number: 1
  skip: true   # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - xtensor 
    - xtensor-python 
    - numpy 1.14.*
    - pip
    - pybind11
    - python
    - fftw >=3

  run:
    - pybind11 >=2.0.1
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - lsdtt_xtensor_python
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://lsdtopotools.github.io
  summary: This is an attempt to port LSDTT to Python
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgailleton
